apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260619-200213-govc4y4i4p1o-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260619-200213-govc4y4i4p1o.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260619-200213-govc4y4i4p1o-service
            port:
              number: 80
